my_list=('p','r','o','g','r','a','m','m','e')
print(my_list[2:5])
print(my_list[5:])
print(my_list[:])
list1=[10,20,30,40,50]
list1.insert(1,70)
print('inserted elements in the lists:',list1)
list1.sort()
print('sorted elements in the list is:',list1)
list1.reverse()
print('reversed elements in the lists is:',list1.pop(3,))
print('removed elements in the lists is:',list1)
print('largest elements in the lists is:',max(list1))
print('smallest elements in the lists is:',min(list1))